[package]
name = "rend_ox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.0"
bytemuck = "1.13.1"
nannou = "0.18.1" # While waiting for real wgpu support